"""Add percentage_12th

Revision ID: 10678dda529d
Revises: 817fdd8fa04e
Create Date: 2025-12-13 23:58:59.333720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10678dda529d'
down_revision: Union[str, None] = '817fdd8fa04e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('percentage_12th', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'percentage_12th')
    # ### end Alembic commands ###
