"""remove_roll_number_from_student_profiles

Revision ID: 33a99ffa1a7f
Revises: 60e09cdcffad
Create Date: 2025-12-10 21:08:42.182761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '33a99ffa1a7f'
down_revision: Union[str, None] = '60e09cdcffad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('roll_number', table_name='student_profiles')
    op.drop_column('student_profiles', 'roll_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('roll_number', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('roll_number', 'student_profiles', ['roll_number'], unique=True)
    # ### end Alembic commands ###
