"""add_required_profile_fields_to_scholarships

Revision ID: 60e09cdcffad
Revises: 88126bad55b8
Create Date: 2025-12-10 21:01:29.540218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e09cdcffad'
down_revision: Union[str, None] = '88126bad55b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('required_profile_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'required_profile_fields')
    # ### end Alembic commands ###
