"""add_scholarship_switch_count

Revision ID: 817fdd8fa04e
Revises: 0da521edee79
Create Date: 2025-12-13 20:04:36.799799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817fdd8fa04e'
down_revision: Union[str, None] = '0da521edee79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('scholarship_switch_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'scholarship_switch_count')
    # ### end Alembic commands ###
