"""add_missing_scholarship_columns

Revision ID: a585200efa64
Revises: 5297c0ee00ac
Create Date: 2025-12-05 00:31:00.729186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a585200efa64'
down_revision: Union[str, None] = '5297c0ee00ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('min_12th_percentage', sa.Float(), nullable=True))
    op.add_column('scholarships', sa.Column('min_cgpa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'min_cgpa')
    op.drop_column('scholarships', 'min_12th_percentage')
    # ### end Alembic commands ###
