"""add_instructions_to_doc_requirements

Revision ID: bdd776d90fcb
Revises: beedec674d8f
Create Date: 2025-12-13 18:55:24.161746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd776d90fcb'
down_revision: Union[str, None] = 'beedec674d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarship_document_requirements', sa.Column('instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarship_document_requirements', 'instructions')
    # ### end Alembic commands ###
