"""Add notices table

Revision ID: beedec674d8f
Revises: fdde2fa1d536
Create Date: 2025-12-11 23:31:05.799427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notices_id'), table_name='notices')
    op.drop_table('notices')
    # ### end Alembic commands ###


# revision identifiers, used by Alembic.
    # ### end Alembic commands ###
