"""Add application_link to scholarships

Revision ID: fdde2fa1d536
Revises: add_batch_fields
Create Date: 2025-12-11 22:43:09.090467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdde2fa1d536'
down_revision: Union[str, None] = 'add_batch_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scholarships', sa.Column('application_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scholarships', 'application_link')
    # ### end Alembic commands ###
